<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Strict//EN'
'http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd'>
	
	current_exception - 1.61.0
	
  
    
  
  
  
  
  Boost
  C++ Libraries
  
  
  ...one of the most highly
  regarded and expertly designed C++ library projects in the
  world.  Herb Sutter and Andrei
  Alexandrescu, C++
  Coding Standards
  
  
This is the documentation for an old version of Boost.
                Click here to view this page for the latest version.
Boost Exception
current_exception
include <boost/exception_ptr.hpp>
namespace
boost
    {
    exception_ptr current_exception();
    }
Requirements:
The current_exception function must not be called outside of a catch block.
In addition, to safely copy an exception from one thread to another, if the exception object is copied by current_exception or copy_exception, the two copies must not have shared state. Exceptions that have value-type semantics (as well as the boost::exception type itself) satisfy this requirement.
Returns:
 An exception_ptr that refers to the currently handled exception or a copy of the currently handled exception.
 If the function needs to allocate memory and the attempt fails, it returns an exception_ptr that refers to an instance of std::bad_alloc.
Throws:
Nothing.
Notes:
 It is unspecified whether the return values of two successive calls to current_exception refer to the same exception object.
 Correct implementation of current_exception may require compiler support, unless enable_current_exception was used at the time the currently handled exception object was passed to throw. Whenever current_exception fails to properly copy the current exception object, it returns an exception_ptr to an object of type that is as close as possible to the original exception type, using unknown_exception as a final fallback. All such types derive from boost::exception, and: if the original exception object derives from boost::exception, then the boost::exception sub-object of the object referred to by the returned exception_ptr is initialized by the boost::exception copy constructor;
 if available, the exception contains the std::type_info of the original exception object, accessible through get_error_info<original_exception_type>.
See also: Boost Exception | boost/exception_ptr.hpp | copy_exception | enable_current_exception | Frequently Asked Questions | original_exception_type | unknown_exception
Copyright (c) 2006-2009 by Emil Dotchevski and Reverge Studios, Inc.
Distributed under the Boost Software License, Version 1.0.
